server:
  rootPath: /api/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: server/src/main/resources/keystores/keystore.jks
      keyStorePassword: p@ssw0rd
      validateCerts: false

logging:
  level: INFO