server:
  rootPath: /api/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: keystore.jks
      keyStorePassword: p@ssw0rd
      validateCerts: false

logging:
  level: INFO